#!/bin/sh
#$cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

while true; do
    runApplication reconstructPar -newTimes
    rm log.reconstructPar
    echo "Waiting for 5 minutes"
    sleep 300
done

# ----------------------------------------------------------------- end-of-file
