#!/bin/bash

sudo add-apt-repository "http://dl.openfoam.org/ubuntu dev"
sudo add-apt-repository "http://dl.openfoam.org/ubuntu9"
sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
sudo add-apt-repository http://dl.openfoam.org/ubuntu
sudo apt-get update
sudo apt-get -y install openfoam-dev
sudo apt-get -y install openfoam9
sudo apt-get -y install openfoam10
sudo apt-get -y install openfoam11
# of 2112 and 2106
sudo apt-get -y install curl
curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
wget -q -O - https://dl.openfoam/add-debian-repo.sh | sudo bash
sudo apt-get -y install openfoam2106-default
sudo apt-get -y install openfoam2112-default
sudo apt-get -y install openfoam2206-default
