#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install -y net-tools
sudo apt install -y git
sudo ../clusterResources/MLNX_OFED_LINUX-5.8-1.1.2.1-ubuntu22.04-x86_64/mlnxofedinstall --force
sudo /etc/init.d/openibd restart
sudo cp ~/clusterResources/modules /etc/modules
sudo ifconfig ibp216s0 10.0.0.11/24
sudo ./installX2go
sudo ./mkdirNFSClient
sudo ./shortcutsVim
sudo ./handyPackages
sudo ./installOFDev
sudo ./echoJbashrc
sudo ./installSalomeDep
sudo ./installParaviewDep

