#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install -y net-tools
sudo apt install -y git
sudo ./installInfinibandPackages
sudo /etc/init.d/opensm restart
sudo cp ~/clusterResources/modules /etc/modules
sudo ./installX2go
sudo ./mkdirNFSClient
sudo ./shortcutsVim
sudo ./handyPackages
sudo ./installOFDev
sudo ./echoJbashrc
sudo ./installSalomeDep
sudo ./installParaviewDep

