#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install -y net-tools
sudo apt install -y git
#cd ~
#git clone http://www.github.com/jfp6/.jSet
sudo ./installX2go
sudo ./mkdirNFSClient
sudo ./shortcutsVim
sudo ./handyPackages
sudo ./installOFDev
sudo ./echoJbashrc
sudo ./installSalomeDep
sudo ./installParaviewDep

