#!/bin/bash
echo "
      J. Prince 11/14/2013
     "

USAGE="
      USAGE: $0 -m <name>
"

# Use getopts to pass the flags to variables
while getopts "m:" opt; do
  case $opt in
    m) if [ -n $OPTARG ]; then
	MACHINE=$OPTARG
	fi
      ;;
    \?)
      echo "$USAGE" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ $MACHINE == "aluminum" ]
    then
    echo "Start Aluminum"
    sudo mount /dev/sdc /media/cfd/work
    sudo mount /dev/sdd1 /media/cfd/bach
    sudo mount /dev/sde1 /media/cfd/vivaldi
    sudo mount /dev/sda1 /media/cfd/haydn

    sudo exportfs -a
    sudo service nfs-kernel-server start
fi

if [ $MACHINE == "aluminumDrives" ]
    then
    echo "Start Aluminum drives"
    # Mount drives from Rhodium
    sudo mount 172.17.1.239:/media/cfd/chopin /mnt/nfs/chopin
    sudo mount 172.17.1.239:/media/cfd/mozart /mnt/nfs/mozart
    sudo mount 172.17.1.239:/media/cfd/telemann /mnt/nfs/telemann
    sudo mount 172.17.1.239:/media/cfd/handel /mnt/nfs/handel
    sudo mount 172.17.1.239:/media/cfd/liszt /mnt/nfs/liszt
    sudo mount 172.17.1.239:/media/cfd/debussy /mnt/nfs/debussy

    # Mount drives from Lithium
    sudo mount 172.17.1.243:/media/cfd/brahms /mnt/nfs/brahms
    sudo mount 172.17.1.243:/media/cfd/rameau /mnt/nfs/rameau
    sudo mount 172.17.1.243:/media/cfd/scarlatti /mnt/nfs/scarlatti
    sudo mount 172.17.1.243:/media/cfd/verdi /mnt/nfs/verdi
    sudo mount 172.17.1.243:/home /mnt/nfs/home
fi

if [ $MACHINE == "nickel" ]
    then
    echo "Start nickel or niobium"
    # Mount drives from Aluminum
    sudo mount 172.17.1.232:/media/cfd/bach /mnt/nfs/bach
    sudo mount 172.17.1.232:/media/cfd/vivaldi /mnt/nfs/vivaldi
    sudo mount 172.17.1.232:/media/cfd/work /mnt/nfs/work
    sudo mount 172.17.1.232:/media/cfd/haydn /mnt/nfs/haydn

    # Mount drives from Rhodium
    sudo mount 172.17.1.239:/media/cfd/chopin /mnt/nfs/chopin
    sudo mount 172.17.1.239:/media/cfd/mozart /mnt/nfs/mozart
    sudo mount 172.17.1.239:/media/cfd/telemann /mnt/nfs/telemann
    sudo mount 172.17.1.239:/media/cfd/handel /mnt/nfs/handel
    sudo mount 172.17.1.239:/media/cfd/liszt /mnt/nfs/liszt
    sudo mount 172.17.1.239:/media/cfd/debussy /mnt/nfs/debussy

    # Mount drives from Lithium
    sudo mount 172.17.1.243:/media/cfd/brahms /mnt/nfs/brahms
    sudo mount 172.17.1.243:/media/cfd/rameau /mnt/nfs/rameau
    sudo mount 172.17.1.243:/media/cfd/scarlatti /mnt/nfs/scarlatti
    sudo mount 172.17.1.243:/media/cfd/verdi /mnt/nfs/verdi
    sudo mount 172.17.1.243:/home /mnt/nfs/home

    sudo exportfs -a
    sudo service nfs-kernel-server start
    sudo /etc/init.d/opensm start
fi

if [ $MACHINE == "gold" ]
    then
    echo "Start gold"
    # Mount drives from Aluminum
    sudo mount 172.17.1.232:/media/cfd/bach /mnt/nfs/bach
    sudo mount 172.17.1.232:/media/cfd/vivaldi /mnt/nfs/vivaldi
    sudo mount 172.17.1.232:/media/cfd/work /mnt/nfs/work
    sudo mount 172.17.1.232:/media/cfd/haydn /mnt/nfs/haydn

    # Mount drives from Rhodium
    sudo mount 10.0.0.9:/media/cfd/chopin /mnt/nfs/chopin
    sudo mount 10.0.0.9:/media/cfd/mozart /mnt/nfs/mozart
    sudo mount 10.0.0.9:/media/cfd/telemann /mnt/nfs/telemann
    sudo mount 10.0.0.9:/media/cfd/handel /mnt/nfs/handel
    sudo mount 10.0.0.9:/media/cfd/liszt /mnt/nfs/liszt
    sudo mount 10.0.0.9:/media/cfd/debussy /mnt/nfs/debussy

    # Mount drives from Lithium
    sudo mount 10.0.0.13:/media/cfd/brahms /mnt/nfs/brahms
    sudo mount 10.0.0.13:/media/cfd/rameau /mnt/nfs/rameau
    sudo mount 10.0.0.13:/media/cfd/scarlatti /mnt/nfs/scarlatti
    sudo mount 10.0.0.13:/media/cfd/verdi /mnt/nfs/verdi
    sudo mount 10.0.0.13:/home /mnt/nfs/home

    sudo exportfs -a
    sudo service nfs-kernel-server start
    sudo /etc/init.d/opensm start
fi

if [ $MACHINE == "desktop" ]
    then
    echo "Start desktop client"
    # Mount drives from Aluminum
    sudo mount 172.17.1.232:/media/cfd/bach /mnt/nfs/bach
    sudo mount 172.17.1.232:/media/cfd/vivaldi /mnt/nfs/vivaldi
    sudo mount 172.17.1.232:/media/cfd/work /mnt/nfs/work
    sudo mount 172.17.1.232:/media/cfd/haydn /mnt/nfs/haydn

    # Mount drives from Rhodium
    sudo mount 172.17.1.239:/media/cfd/chopin /mnt/nfs/chopin
    sudo mount 172.17.1.239:/media/cfd/mozart /mnt/nfs/mozart
    sudo mount 172.17.1.239:/media/cfd/telemann /mnt/nfs/telemann
    sudo mount 172.17.1.239:/media/cfd/handel /mnt/nfs/handel
    sudo mount 172.17.1.239:/media/cfd/liszt /mnt/nfs/liszt
    sudo mount 172.17.1.239:/media/cfd/debussy /mnt/nfs/debussy

    # Mount drives from Lithium
    sudo mount 172.17.1.243:/media/cfd/brahms /mnt/nfs/brahms
    sudo mount 172.17.1.243:/media/cfd/rameau /mnt/nfs/rameau
    sudo mount 172.17.1.243:/media/cfd/scarlatti /mnt/nfs/scarlatti
    sudo mount 172.17.1.243:/media/cfd/verdi /mnt/nfs/verdi
    sudo mount 172.17.1.243:/home /mnt/nfs/home

    sudo exportfs -a
    sudo service nfs-kernel-server start
fi

if [ $MACHINE == "platinum" ]
    then
    echo "Start platinum"
    # Mount drives from Aluminum
    sudo mount 172.17.1.232:/media/cfd/bach /mnt/nfs/bach
    sudo mount 172.17.1.232:/media/cfd/vivaldi /mnt/nfs/vivaldi
    sudo mount 172.17.1.232:/media/cfd/work /mnt/nfs/work
    sudo mount 172.17.1.232:/media/cfd/haydn /mnt/nfs/haydn

    # Mount drives from Rhodium
    sudo mount 10.0.0.9:/media/cfd/chopin /mnt/nfs/chopin
    sudo mount 10.0.0.9:/media/cfd/mozart /mnt/nfs/mozart
    sudo mount 10.0.0.9:/media/cfd/telemann /mnt/nfs/telemann
    sudo mount 10.0.0.9:/media/cfd/handel /mnt/nfs/handel
    sudo mount 10.0.0.9:/media/cfd/liszt /mnt/nfs/liszt
    sudo mount 10.0.0.9:/media/cfd/debussy /mnt/nfs/debussy

    # Mount drives from Lithium
    sudo mount 10.0.0.13:/media/cfd/brahms /mnt/nfs/brahms
    sudo mount 10.0.0.13:/media/cfd/rameau /mnt/nfs/rameau
    sudo mount 10.0.0.13:/media/cfd/scarlatti /mnt/nfs/scarlatti
    sudo mount 10.0.0.13:/media/cfd/verdi /mnt/nfs/verdi
    sudo mount 10.0.0.13:/home /mnt/nfs/home

    nohup pypi-server -p 8080 ~/pypiRepository/ &

    sudo exportfs -a
    sudo service nfs-kernel-server start
    sudo /etc/init.d/opensm start
fi

if [ $MACHINE == "rhodium" ]
    then
    echo "Start Rhodium"
    sudo mount /dev/sda1 /media/cfd/mozart
    sudo mount /dev/sdb1 /media/cfd/chopin
    sudo mount /dev/sdc1 /media/cfd/telemann
    sudo mount /dev/nvme1n1p1 /media/cfd/liszt
    sudo mount /dev/nvme2n1p1 /media/cfd/debussy
    sudo mount /dev/nvme3n1p1 /media/cfd/handel

    sudo exportfs -a
    sudo service nfs-kernel-server start
    sudo /etc/init.d/opensm start

    # Mount drives from Aluminum
    sudo mount 172.17.1.232:/media/cfd/bach /mnt/nfs/bach
    sudo mount 172.17.1.232:/media/cfd/vivaldi /mnt/nfs/vivaldi
    sudo mount 172.17.1.232:/media/cfd/work /mnt/nfs/work
    sudo mount 172.17.1.232:/media/cfd/haydn /mnt/nfs/haydn

    xsetroot -solid "#333333"
fi

if [ $MACHINE == "rhodiumDrives" ]
    then
    echo "Start Rhodium drives only"
    # Mount drives from Lithium
    #sudo mount 172.17.1.243:/media/cfd/brahms /mnt/nfs/brahms
    #sudo mount 172.17.1.243:/media/cfd/rameau /mnt/nfs/rameau
    #sudo mount 172.17.1.243:/media/cfd/scarlatti /mnt/nfs/scarlatti
    #sudo mount 172.17.1.243:/media/cfd/verdi /mnt/nfs/verdi
    #sudo mount 172.17.1.243:/home /mnt/nfs/home
    sudo mount 10.0.0.13:/media/cfd/brahms /mnt/nfs/brahms
    sudo mount 10.0.0.13:/media/cfd/rameau /mnt/nfs/rameau
    sudo mount 10.0.0.13:/media/cfd/scarlatti /mnt/nfs/scarlatti
    sudo mount 10.0.0.13:/media/cfd/verdi /mnt/nfs/verdi
    sudo mount 10.0.0.13:/home /mnt/nfs/home

    # Start cluster utilization monitor
    nohup /home/cfd/brahms/cpu/clusterStatus.sh > /home/cfd/brahms/cpu/run.out &
fi

if [ $MACHINE == "lithium" ]
    then
    echo "Start Lithium"
    sudo mount /dev/sda1 /media/cfd/brahms
    sudo mount /dev/sdc1 /media/cfd/rameau
    sudo mount /dev/sdb1 /media/cfd/scarlatti
    sudo mount /dev/nvme1n1p1 /media/cfd/verdi

    sudo exportfs -a
    sudo service nfs-kernel-server start
    sudo /etc/init.d/opensm start

    # Mount drives from Aluminum
    sudo mount 172.17.1.232:/media/cfd/bach /mnt/nfs/bach
    sudo mount 172.17.1.232:/media/cfd/vivaldi /mnt/nfs/vivaldi
    sudo mount 172.17.1.232:/media/cfd/work /mnt/nfs/work
    sudo mount 172.17.1.232:/media/cfd/haydn /mnt/nfs/haydn

    # Mount drives from Rhodium
    sudo mount 10.0.0.9:/media/cfd/chopin /mnt/nfs/chopin
    sudo mount 10.0.0.9:/media/cfd/mozart /mnt/nfs/mozart
    sudo mount 10.0.0.9:/media/cfd/telemann /mnt/nfs/telemann
    sudo mount 10.0.0.9:/media/cfd/handel /mnt/nfs/handel
    sudo mount 10.0.0.9:/media/cfd/liszt /mnt/nfs/liszt
    sudo mount 10.0.0.9:/media/cfd/debussy /mnt/nfs/debussy

    xsetroot -solid "#333333"
fi
