#!/bin/bash

ssh cfd@gold 'rm -rf ~/.jSet'
ssh cfd@silver 'rm -rf ~/.jSet'
ssh cfd@nickel 'rm -rf ~/.jSet'
ssh cfd@niobium 'rm -rf ~/.jSet'
ssh cfd@platinum 'rm -rf ~/.jSet'
ssh cfd@palladium 'rm -rf ~/.jSet'
ssh cfd@titanium 'rm -rf ~/.jSet'
ssh cfd@rhodium 'rm -rf ~/.jSet'
ssh cfd@cobalt 'rm -rf ~/.jSet'
ssh cfd@scandium 'rm -rf ~/.jSet'
ssh cfd@uranium 'rm -rf ~/.jSet'
ssh cfd@aluminum 'rm -rf ~/.jSet'
ssh cfd@lithium 'rm -rf ~/.jSet'
ssh cfd@brass 'rm -rf ~/.jSet'
ssh cfd@172.17.1.97 'rm -rf ~/.jSet'

scp -r ~/.jSet cfd@gold:~/.
scp -r ~/.jSet cfd@silver:~/.
scp -r ~/.jSet cfd@nickel:~/.
scp -r ~/.jSet cfd@niobium:~/.
scp -r ~/.jSet cfd@platinum:~/.
scp -r ~/.jSet cfd@palladium:~/.
scp -r ~/.jSet cfd@titanium:~/.
scp -r ~/.jSet cfd@rhodium:~/.
scp -r ~/.jSet cfd@cobalt:~/.
scp -r ~/.jSet cfd@scandium:~/.
scp -r ~/.jSet cfd@uranium:~/.
scp -r ~/.jSet cfd@aluminum:~/.
scp -r ~/.jSet cfd@lithium:~/.
scp -r ~/.jSet cfd@brass:~/.
scp -r ~/.jSet cfd@172.17.1.97:~/.

ssh cfd@zinc 'rm -rf ~/.jSet'
scp -r ~/.jSet cfd@zinc:~/.
